name: app_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto-Regular.ttf
        - asset: assets/fonts/Doto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Doto-ExtraLight.ttf
          weight: 200
  assets:
    - assets/images/image_1.jpg
    - assets/images/image_2.jpg
    - assets/images/image_3.jpg
